backend:
  name: git-gateway
  repo: Augustin880/filigranduo
  branch: main
  auth_type: implicit
  app_id: Ov23liI4j6gtxlQt4Hfg
  base_url: https://filigranduo.netlify.app
  site_id: 117f169f-fb40-4611-9e7a-706339b2c8b7

media_folder: "img"
public_folder: "/img"

collections:
  - name: "performances"
    label: "Performances"
    files:
      - file: "data/performances.json"
        label: "Performances List"
        name: "performances"
        fields:
          - label: "Performances"
            name: "performances"
            widget: "list"
            summary: "{{title}} - {{date}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
