backend:
  name: github
  repo: Augustin880/filigranduo
  branch: main
  auth_type: implicit
  app_id: Ov23liI4j6gtxlQt4Hfg

media_folder: "img"
public_folder: "img"

collections:
  - name: "performances"
    label: "Performances"
    files:
      - file: "data/performances.json"
        label: "Performances JSON"
        name: "performances"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
