backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "performances"
    label: "Performances"
    files:
      - file: "data/performances.json"
        label: "Performances List"
        name: "performances"
        fields:
          - label: "Performances"
            name: "performances"
            widget: "list"
            summary: "{{title}} - {{date}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }

